// GENERATED by assets/portraits/make-portrait-index.cjs — do not edit by hand.
// Re-run it whenever the portrait pack changes; a test checks this list
// against the directory, so a stale index fails the suite.
import p0_aladim from './assets/portraits/aladim.png';
import p1_arunpeel from './assets/portraits/arunpeel.png';
import p2_auclair from './assets/portraits/auclair.png';
import p3_bechet from './assets/portraits/bechet.png';
import p4_chaima from './assets/portraits/chaima.png';
import p5_christopher from './assets/portraits/christopher.png';
import p6_clifton from './assets/portraits/clifton.png';
import p7_clovette from './assets/portraits/clovette.png';
import p8_connielee from './assets/portraits/connielee.png';
import p9_dominykas from './assets/portraits/dominykas.png';
import p10_dorothy from './assets/portraits/dorothy.png';
import p11_elridge from './assets/portraits/elridge.png';
import p12_enid from './assets/portraits/enid.png';
import p13_fascination from './assets/portraits/fascination.png';
import p14_gorgiou from './assets/portraits/gorgiou.png';
import p15_gristwood from './assets/portraits/gristwood.png';
import p16_jannings from './assets/portraits/jannings.png';
import p17_jc from './assets/portraits/jc.png';
import p18_laidlaw from './assets/portraits/laidlaw.png';
import p19_leo from './assets/portraits/leo.png';
import p20_marinette from './assets/portraits/marinette.png';
import p21_medea from './assets/portraits/medea.png';
import p22_medusa from './assets/portraits/medusa.png';
import p23_mireya from './assets/portraits/mireya.png';
import p24_morgan from './assets/portraits/morgan.png';
import p25_naenia from './assets/portraits/naenia.png';
import p26_neville from './assets/portraits/neville.png';
import p27_orsolina from './assets/portraits/orsolina.png';
import p28_poppy from './assets/portraits/poppy.png';
import p29_porter from './assets/portraits/porter.png';
import p30_renira from './assets/portraits/renira.png';
import p31_rose from './assets/portraits/rose.png';
import p32_saliba from './assets/portraits/saliba.png';
import p33_slee from './assets/portraits/slee.png';
import p34_spencerhobson from './assets/portraits/spencerhobson.png';
import p35_sulochana from './assets/portraits/sulochana.png';
import p36_sylvia from './assets/portraits/sylvia.png';
import p37_teresa from './assets/portraits/teresa.png';
import p38_tristran from './assets/portraits/tristran.png';
import p39_tryphon from './assets/portraits/tryphon.png';
import p40_valciane from './assets/portraits/valciane.png';
import p41_vasil from './assets/portraits/vasil.png';
import p42_victor from './assets/portraits/victor.png';
import p43_violet from './assets/portraits/violet.png';
import p44_wakefield from './assets/portraits/wakefield.png';
import p45_welland from './assets/portraits/welland.png';
import p46_ysabet from './assets/portraits/ysabet.png';
import p47_zulfiya from './assets/portraits/zulfiya.png';

export const PORTRAIT_FILES: string[] = [
  p0_aladim,
  p1_arunpeel,
  p2_auclair,
  p3_bechet,
  p4_chaima,
  p5_christopher,
  p6_clifton,
  p7_clovette,
  p8_connielee,
  p9_dominykas,
  p10_dorothy,
  p11_elridge,
  p12_enid,
  p13_fascination,
  p14_gorgiou,
  p15_gristwood,
  p16_jannings,
  p17_jc,
  p18_laidlaw,
  p19_leo,
  p20_marinette,
  p21_medea,
  p22_medusa,
  p23_mireya,
  p24_morgan,
  p25_naenia,
  p26_neville,
  p27_orsolina,
  p28_poppy,
  p29_porter,
  p30_renira,
  p31_rose,
  p32_saliba,
  p33_slee,
  p34_spencerhobson,
  p35_sulochana,
  p36_sylvia,
  p37_teresa,
  p38_tristran,
  p39_tryphon,
  p40_valciane,
  p41_vasil,
  p42_victor,
  p43_violet,
  p44_wakefield,
  p45_welland,
  p46_ysabet,
  p47_zulfiya
];

/** The portraits' own names, index for index with PORTRAIT_FILES. */
export const PORTRAIT_NAMES: string[] = [
  'aladim',
  'arunpeel',
  'auclair',
  'bechet',
  'chaima',
  'christopher',
  'clifton',
  'clovette',
  'connielee',
  'dominykas',
  'dorothy',
  'elridge',
  'enid',
  'fascination',
  'gorgiou',
  'gristwood',
  'jannings',
  'jc',
  'laidlaw',
  'leo',
  'marinette',
  'medea',
  'medusa',
  'mireya',
  'morgan',
  'naenia',
  'neville',
  'orsolina',
  'poppy',
  'porter',
  'renira',
  'rose',
  'saliba',
  'slee',
  'spencerhobson',
  'sulochana',
  'sylvia',
  'teresa',
  'tristran',
  'tryphon',
  'valciane',
  'vasil',
  'victor',
  'violet',
  'wakefield',
  'welland',
  'ysabet',
  'zulfiya'
];
