// GENERATED by assets/portraits/make-portrait-index.cjs — do not edit by hand.
// Re-run it whenever the portrait pack changes; a test checks this list
// against the directory, so a stale index fails the suite.
export const PORTRAIT_FILES: string[] = [];
